[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.2.1"
authors = ["Nicolas Buitrago <mail@nsbuitrago.xyz>"]
license = "MIT"
description = "RMA Kinetic Models"
repository = "https://github.com/nsbuitrago/rma-kinetics-rs"
homepage = "https://github.com/nsbuitrago/rma-kinetics-rs"
edition = "2024"

[workspace.dependencies]
differential-equations = "0.6.1"
pyo3 = "0.27.2"
numpy = "0.27.1"
thiserror = "2.0.19"
derive_builder = "0.20.2"
rand = "0.9.5"
rand_distr = "0.5.1"
serde = { version = "1.0.229", features = ["derive"] }
rma-kinetics = { version = "0.2.1", path = "crates/rma-kinetics" }
rma-kinetics-derive = { version = "0.2.1", path = "crates/rma-kinetics-derive" }
